name: Bug Report for solder.py
description: File a bug report for solder.py
title: "[BUG]: "
labels: ["TYPE: BUG", "STATUS: NOT STARTED", "PRIORITY: N/A"]
body:
  - type: textarea
    id: Describe-the-bug
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: To-Reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder:
      value: "1. Go to '...'

2. Click on '....'

3. Scroll down to '....'

4. See error"
    validations:
      required: true
  - type: textarea
    id: Expected-behavior
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: solderversion
    attributes:
      label: solder.py Version
      description: What version of solder.py are you running?
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS/Container are you seeing the problem on?
      multiple: true
      options:
        - Official Docker
        - Windows
        - Linux
        - MAC
        - BSD
        - Docker
        - LVC
    validations:
      required: false
  - type: markdown
    attributes:
      value: "We only guarantee support trough our official docker container"
  - type: textarea
    id: Screenshots
    attributes:
      label: Screenshots
      description:
      placeholder: "Add screenshots to help explain your problem here. If you don't, we may not help you."
  - type: textarea
    id: Enviroment Variables
    attributes:
      label: Provide censored enviroment variables here
      description:
      placeholder: Paste variables here
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Snippet of the issue in Logs from your docker container
      description:
      placeholder: Paste log here
      render: shell
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Issues not providing the required files will not get help"