name: Enhancement request solder.py
description: File a enhancement request solder.py
title: "[ENHANCEMENT]: "
labels: ["TYPE: ENHANCEMENT", "STATUS: NOT STARTED", "PRIORITY: N/A"]
body:
  - type: textarea
    id: prob
    attributes:
      label: Is your enhancement request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: sol
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alt
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: input
    id: solderversion
    attributes:
      label: solder.py Version
      description: What version of solder.py are you running?
    validations:
      required: true
  - type: textarea
    id: Screenshots
    attributes:
      label: Screenshots
      description:
      placeholder: "Add screenshots to help explain."
  - type: textarea
    id: cont
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false